//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.9.0
// @generated from file beerproto/v1/boil.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { TimeType, VolumeType } from "./measureable_units_pb.js";
import { BoilStepType } from "./boil_step_pb.js";

/**
 * BoilProcedureType defines the procedure for performing a boil. A boil procedure with no steps is the same as a standard single step boil
 *
 * @generated from message beerproto.v1.BoilProcedureType
 */
export const BoilProcedureType = /*@__PURE__*/ proto3.makeMessageType(
  "beerproto.v1.BoilProcedureType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "pre_boil_size", kind: "message", T: VolumeType },
    { no: 3, name: "boil_time", kind: "message", T: TimeType },
    { no: 4, name: "boil_steps", kind: "message", T: BoilStepType, repeated: true },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 7, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

