//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.3.1
// @generated from file beerproto/v1/boil_step.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { AcidityType, GravityType, TemperatureType, TimeType } from "./measureable_units_pb.js";

/**
 * @generated from enum beerproto.v1.BoilStepTypeChillingType
 */
export const BoilStepTypeChillingType = proto3.makeEnum(
  "beerproto.v1.BoilStepTypeChillingType",
  [
    {no: 0, name: "BOIL_STEP_TYPE_CHILLING_TYPE_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "BOIL_STEP_TYPE_CHILLING_TYPE_BATCH", localName: "BATCH"},
    {no: 2, name: "BOIL_STEP_TYPE_CHILLING_TYPE_INLINE", localName: "INLINE"},
  ],
);

/**
 * BoilStepType - a per step representation of a boil process, can be used to support preboil steps, non-boiling pasteurization steps, boiling, whirlpool steps, and chilling
 *
 * @generated from message beerproto.v1.BoilStepType
 */
export const BoilStepType = proto3.makeMessageType(
  "beerproto.v1.BoilStepType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "end_gravity", kind: "message", T: GravityType },
    { no: 3, name: "chilling_type", kind: "enum", T: proto3.getEnumType(BoilStepTypeChillingType) },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "end_temperature", kind: "message", T: TemperatureType },
    { no: 6, name: "ramp_time", kind: "message", T: TimeType },
    { no: 7, name: "step_time", kind: "message", T: TimeType },
    { no: 8, name: "start_gravity", kind: "message", T: GravityType },
    { no: 9, name: "start_ph", kind: "message", T: AcidityType },
    { no: 10, name: "end_ph", kind: "message", T: AcidityType },
    { no: 11, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 12, name: "start_temperature", kind: "message", T: TemperatureType },
  ],
);

