//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.3.1
// @generated from file beerproto/v1/expression.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * @generated from enum beerproto.v1.BinaryArithmetic
 */
export declare enum BinaryArithmetic {
  /**
   * @generated from enum value: BINARY_ARITHMETIC_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: BINARY_ARITHMETIC_ADDITION = 1;
   */
  ADDITION = 1,

  /**
   * @generated from enum value: BINARY_ARITHMETIC_SUBTRACTION = 2;
   */
  SUBTRACTION = 2,

  /**
   * @generated from enum value: BINARY_ARITHMETIC_MULTIPLICATION = 3;
   */
  MULTIPLICATION = 3,

  /**
   * @generated from enum value: BINARY_ARITHMETIC_DIVISION = 4;
   */
  DIVISION = 4,
}

/**
 * @generated from message beerproto.v1.UnaryExpression
 */
export declare class UnaryExpression extends Message<UnaryExpression> {
  /**
   * @generated from oneof beerproto.v1.UnaryExpression.value
   */
  value: {
    /**
     * @generated from field: double double = 1;
     */
    value: number;
    case: "double";
  } | {
    /**
     * @generated from field: float float = 2;
     */
    value: number;
    case: "float";
  } | {
    /**
     * @generated from field: int32 int32 = 3;
     */
    value: number;
    case: "int32";
  } | {
    /**
     * @generated from field: int64 int64 = 4;
     */
    value: bigint;
    case: "int64";
  } | {
    /**
     * @generated from field: uint32 uint32 = 5;
     */
    value: number;
    case: "uint32";
  } | {
    /**
     * @generated from field: uint64 uint64 = 6;
     */
    value: bigint;
    case: "uint64";
  } | {
    /**
     * @generated from field: bool bool = 7;
     */
    value: boolean;
    case: "bool";
  } | {
    /**
     * @generated from field: string string = 8;
     */
    value: string;
    case: "string";
  } | {
    /**
     * @generated from field: bytes bytes = 9;
     */
    value: Uint8Array;
    case: "bytes";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<UnaryExpression>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beerproto.v1.UnaryExpression";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): UnaryExpression;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): UnaryExpression;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): UnaryExpression;

  static equals(a: UnaryExpression | PlainMessage<UnaryExpression> | undefined, b: UnaryExpression | PlainMessage<UnaryExpression> | undefined): boolean;
}

/**
 * @generated from message beerproto.v1.BinaryExpression
 */
export declare class BinaryExpression extends Message<BinaryExpression> {
  /**
   * @generated from field: beerproto.v1.BinaryArithmetic operator = 1;
   */
  operator: BinaryArithmetic;

  /**
   * @generated from oneof beerproto.v1.BinaryExpression.left
   */
  left: {
    /**
     * @generated from field: beerproto.v1.BinaryExpression binary_left = 10;
     */
    value: BinaryExpression;
    case: "binaryLeft";
  } | {
    /**
     * @generated from field: beerproto.v1.UnaryExpression unary_left = 11;
     */
    value: UnaryExpression;
    case: "unaryLeft";
  } | {
    /**
     * @generated from field: beerproto.v1.ValueExpression value_left = 12;
     */
    value: ValueExpression;
    case: "valueLeft";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from oneof beerproto.v1.BinaryExpression.right
   */
  right: {
    /**
     * @generated from field: beerproto.v1.BinaryExpression binary_right = 20;
     */
    value: BinaryExpression;
    case: "binaryRight";
  } | {
    /**
     * @generated from field: beerproto.v1.UnaryExpression unary_right = 21;
     */
    value: UnaryExpression;
    case: "unaryRight";
  } | {
    /**
     * @generated from field: beerproto.v1.ValueExpression value_right = 22;
     */
    value: ValueExpression;
    case: "valueRight";
  } | { case: undefined; value?: undefined };

  constructor(data?: PartialMessage<BinaryExpression>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beerproto.v1.BinaryExpression";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): BinaryExpression;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): BinaryExpression;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): BinaryExpression;

  static equals(a: BinaryExpression | PlainMessage<BinaryExpression> | undefined, b: BinaryExpression | PlainMessage<BinaryExpression> | undefined): boolean;
}

/**
 * @generated from message beerproto.v1.ValueExpression
 */
export declare class ValueExpression extends Message<ValueExpression> {
  constructor(data?: PartialMessage<ValueExpression>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beerproto.v1.ValueExpression";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): ValueExpression;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): ValueExpression;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): ValueExpression;

  static equals(a: ValueExpression | PlainMessage<ValueExpression> | undefined, b: ValueExpression | PlainMessage<ValueExpression> | undefined): boolean;
}

