//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.3.1
// @generated from file beerproto/v1/fermentation_step.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { AcidityType, GravityType, PercentType, TemperatureType, TimeType } from "./measureable_units_pb.js";

/**
 * FermentationStepType - a per step representation of a fermentation action
 *
 * @generated from message beerproto.v1.FermentationStepType
 */
export const FermentationStepType = proto3.makeMessageType(
  "beerproto.v1.FermentationStepType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "end_temperature", kind: "message", T: TemperatureType },
    { no: 4, name: "step_time", kind: "message", T: TimeType },
    { no: 5, name: "free_rise", kind: "scalar", T: 8 /* ScalarType.BOOL */ },
    { no: 6, name: "start_gravity", kind: "message", T: GravityType },
    { no: 7, name: "end_gravity", kind: "message", T: GravityType },
    { no: 8, name: "start_ph", kind: "message", T: AcidityType },
    { no: 9, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "start_temperature", kind: "message", T: TemperatureType },
    { no: 11, name: "end_ph", kind: "message", T: AcidityType },
    { no: 12, name: "vessel", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 13, name: "vessel_pressure", kind: "message", T: PercentType },
  ],
);

