//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.3.1
// @generated from file beerproto/v1/fermentation.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { FermentationStepType } from "./fermentation_step_pb.js";

/**
 * FermentationProcedureType defines the procedure for performing fermentation
 *
 * @generated from message beerproto.v1.FermentationProcedureType
 */
export const FermentationProcedureType = proto3.makeMessageType(
  "beerproto.v1.FermentationProcedureType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "fermentation_steps", kind: "message", T: FermentationStepType, repeated: true },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

