//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.9.0
// @generated from file beerproto/v1/mash_step.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { AcidityType, SpecificVolumeType, TemperatureType, TimeType, VolumeType } from "./measureable_units_pb.js";

/**
 * @generated from enum beerproto.v1.MashStepUnit
 */
export const MashStepUnit = /*@__PURE__*/ proto3.makeEnum(
  "beerproto.v1.MashStepUnit",
  [
    {no: 0, name: "MASH_STEP_UNIT_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "MASH_STEP_UNIT_INFUSION", localName: "INFUSION"},
    {no: 2, name: "MASH_STEP_UNIT_TEMPERATURE", localName: "TEMPERATURE"},
    {no: 3, name: "MASH_STEP_UNIT_DECOCTION", localName: "DECOCTION"},
    {no: 4, name: "MASH_STEP_UNIT_SOURING_MASH", localName: "SOURING_MASH"},
    {no: 5, name: "MASH_STEP_UNIT_SOURING_WORT", localName: "SOURING_WORT"},
    {no: 6, name: "MASH_STEP_UNIT_DRAIN_MASH_TUN", localName: "DRAIN_MASH_TUN"},
    {no: 7, name: "MASH_STEP_UNIT_SPARGE", localName: "SPARGE"},
  ],
);

/**
 * MashStepType - a per step representation occurring during the mash
 *
 * @generated from message beerproto.v1.MashStepType
 */
export const MashStepType = /*@__PURE__*/ proto3.makeMessageType(
  "beerproto.v1.MashStepType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "step_time", kind: "message", T: TimeType },
    { no: 3, name: "ramp_time", kind: "message", T: TimeType },
    { no: 4, name: "end_temperature", kind: "message", T: TemperatureType },
    { no: 5, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "infuse_temperature", kind: "message", T: TemperatureType },
    { no: 7, name: "start_ph", kind: "message", T: AcidityType },
    { no: 8, name: "end_ph", kind: "message", T: AcidityType },
    { no: 9, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 10, name: "type", kind: "enum", T: proto3.getEnumType(MashStepUnit) },
    { no: 11, name: "amount", kind: "message", T: VolumeType },
    { no: 12, name: "step_temperature", kind: "message", T: TemperatureType },
    { no: 13, name: "water_grain_ratio", kind: "message", T: SpecificVolumeType },
  ],
);

