//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.3.1
// @generated from file beerproto/v1/mash.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { TemperatureType } from "./measureable_units_pb.js";
import { MashStepType } from "./mash_step_pb.js";

/**
 * This defines the procedure for performing unique mashing processes
 *
 * @generated from message beerproto.v1.MashProcedureType
 */
export const MashProcedureType = proto3.makeMessageType(
  "beerproto.v1.MashProcedureType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "grain_temperature", kind: "message", T: TemperatureType },
    { no: 3, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 4, name: "mash_steps", kind: "message", T: MashStepType, repeated: true },
    { no: 5, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
  ],
);

