//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.9.0
// @generated from file beerproto/v1/packaging_vessel.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { AcidityType, GravityType, TemperatureType, TimeType, VolumeType } from "./measureable_units_pb.js";
import { PackagingGraphicType } from "./packaging_graphic_pb.js";

/**
 * @generated from enum beerproto.v1.PackagingVesselUnit
 */
export const PackagingVesselUnit = /*@__PURE__*/ proto3.makeEnum(
  "beerproto.v1.PackagingVesselUnit",
  [
    {no: 0, name: "PACKAGING_VESSEL_UNIT_UNSPECIFIED", localName: "UNSPECIFIED"},
    {no: 1, name: "PACKAGING_VESSEL_UNIT_KEG", localName: "KEG"},
    {no: 2, name: "PACKAGING_VESSEL_UNIT_BOTTLE", localName: "BOTTLE"},
    {no: 3, name: "PACKAGING_VESSEL_UNIT_CASK", localName: "CASK"},
    {no: 4, name: "PACKAGING_VESSEL_UNIT_TANK", localName: "TANK"},
    {no: 5, name: "PACKAGING_VESSEL_UNIT_FIRKIN", localName: "FIRKIN"},
    {no: 6, name: "PACKAGING_VESSEL_UNIT_OTHER", localName: "OTHER"},
    {no: 7, name: "PACKAGING_VESSEL_UNIT_CAN", localName: "CAN"},
  ],
);

/**
 * PackagingVesselType - a per vessel representation of a packaging process
 *
 * @generated from message beerproto.v1.PackagingVesselType
 */
export const PackagingVesselType = /*@__PURE__*/ proto3.makeMessageType(
  "beerproto.v1.PackagingVesselType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "type", kind: "enum", T: proto3.getEnumType(PackagingVesselUnit) },
    { no: 3, name: "start_gravity", kind: "message", T: GravityType },
    { no: 4, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "package_date", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "step_time", kind: "message", T: TimeType },
    { no: 7, name: "end_gravity", kind: "message", T: GravityType },
    { no: 8, name: "vessel_volume", kind: "message", T: VolumeType },
    { no: 9, name: "vessel_quantity", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 10, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 11, name: "start_ph", kind: "message", T: AcidityType },
    { no: 12, name: "carbonation", kind: "scalar", T: 1 /* ScalarType.DOUBLE */ },
    { no: 13, name: "start_temperature", kind: "message", T: TemperatureType },
    { no: 14, name: "end_ph", kind: "message", T: AcidityType },
    { no: 15, name: "end_temperature", kind: "message", T: TemperatureType },
    { no: 16, name: "graphics", kind: "message", T: PackagingGraphicType, repeated: true },
  ],
);

