//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.9.0
// @generated from file beerproto/v1/packaging.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import { proto3 } from "@bufbuild/protobuf";
import { VolumeType } from "./measureable_units_pb.js";
import { PackagingVesselType } from "./packaging_vessel_pb.js";

/**
 * Describes the procedure for packaging your beverage
 *
 * @generated from message beerproto.v1.PackagingProcedureType
 */
export const PackagingProcedureType = /*@__PURE__*/ proto3.makeMessageType(
  "beerproto.v1.PackagingProcedureType",
  () => [
    { no: 1, name: "id", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 2, name: "name", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 3, name: "packaged_volume", kind: "message", T: VolumeType },
    { no: 4, name: "description", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 5, name: "notes", kind: "scalar", T: 9 /* ScalarType.STRING */ },
    { no: 6, name: "packaging_vessels", kind: "message", T: PackagingVesselType, repeated: true },
  ],
);

