//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.3.1
// @generated from file beerproto/v1/packaging_graphic.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";

/**
 * Representation of a graphic to be placed on a vessel.
 *
 * @generated from message beerproto.v1.PackagingGraphicType
 */
export declare class PackagingGraphicType extends Message<PackagingGraphicType> {
  /**
   * @generated from field: beerproto.v1.PackagingGraphicType.PositionUnit position = 1;
   */
  position: PackagingGraphicType_PositionUnit;

  /**
   * File type
   *
   * @generated from field: beerproto.v1.PackagingGraphicType.GraphicType type = 2;
   */
  type: PackagingGraphicType_GraphicType;

  /**
   * Base64 encoded file.
   *
   * @generated from field: string base64_data = 3;
   */
  base64Data: string;

  /**
   * URLS to hosted version of image.
   *
   * @generated from field: repeated string urls = 4;
   */
  urls: string[];

  /**
   * Dots per inch.
   *
   * @generated from field: int32 dpi = 5;
   */
  dpi: number;

  /**
   * @generated from field: int64 width = 6;
   */
  width: bigint;

  /**
   * @generated from field: int64 height = 7;
   */
  height: bigint;

  /**
   * The unit type which are used for measurements.
   *
   * @generated from field: beerproto.v1.PackagingGraphicType.UnitsType units = 8;
   */
  units: PackagingGraphicType_UnitsType;

  constructor(data?: PartialMessage<PackagingGraphicType>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beerproto.v1.PackagingGraphicType";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): PackagingGraphicType;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): PackagingGraphicType;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): PackagingGraphicType;

  static equals(a: PackagingGraphicType | PlainMessage<PackagingGraphicType> | undefined, b: PackagingGraphicType | PlainMessage<PackagingGraphicType> | undefined): boolean;
}

/**
 * @generated from enum beerproto.v1.PackagingGraphicType.PositionUnit
 */
export declare enum PackagingGraphicType_PositionUnit {
  /**
   * @generated from enum value: POSITION_UNIT_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: POSITION_UNIT_BODY_FRONT = 1;
   */
  BODY_FRONT = 1,

  /**
   * @generated from enum value: POSITION_UNIT_BODY_BACK = 2;
   */
  BODY_BACK = 2,

  /**
   * @generated from enum value: POSITION_UNIT_BODY_WRAP_AROUND = 3;
   */
  BODY_WRAP_AROUND = 3,

  /**
   * @generated from enum value: POSITION_UNIT_NECK_FRONT = 4;
   */
  NECK_FRONT = 4,

  /**
   * @generated from enum value: POSITION_UNIT_NECK_BACK = 5;
   */
  NECK_BACK = 5,

  /**
   * @generated from enum value: POSITION_UNIT_NECK_WRAP_AROUND = 6;
   */
  NECK_WRAP_AROUND = 6,

  /**
   * @generated from enum value: POSITION_UNIT_CAP = 7;
   */
  CAP = 7,

  /**
   * @generated from enum value: POSITION_UNIT_CARRIER = 8;
   */
  CARRIER = 8,
}

/**
 * @generated from enum beerproto.v1.PackagingGraphicType.GraphicType
 */
export declare enum PackagingGraphicType_GraphicType {
  /**
   * @generated from enum value: GRAPHIC_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: GRAPHIC_TYPE_SVG = 1;
   */
  SVG = 1,

  /**
   * @generated from enum value: GRAPHIC_TYPE_SVGZ = 2;
   */
  SVGZ = 2,

  /**
   * @generated from enum value: GRAPHIC_TYPE_AI = 3;
   */
  AI = 3,

  /**
   * @generated from enum value: GRAPHIC_TYPE_CDR = 4;
   */
  CDR = 4,

  /**
   * @generated from enum value: GRAPHIC_TYPE_CDX = 5;
   */
  CDX = 5,

  /**
   * @generated from enum value: GRAPHIC_TYPE_ODG = 6;
   */
  ODG = 6,

  /**
   * @generated from enum value: GRAPHIC_TYPE_EPS = 7;
   */
  EPS = 7,

  /**
   * @generated from enum value: GRAPHIC_TYPE_PDF = 8;
   */
  PDF = 8,

  /**
   * @generated from enum value: GRAPHIC_TYPE_PNG = 9;
   */
  PNG = 9,

  /**
   * @generated from enum value: GRAPHIC_TYPE_JPG = 10;
   */
  JPG = 10,

  /**
   * @generated from enum value: GRAPHIC_TYPE_GIF = 11;
   */
  GIF = 11,
}

/**
 * @generated from enum beerproto.v1.PackagingGraphicType.UnitsType
 */
export declare enum PackagingGraphicType_UnitsType {
  /**
   * @generated from enum value: UNITS_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: UNITS_TYPE_MM = 1;
   */
  MM = 1,

  /**
   * @generated from enum value: UNITS_TYPE_IN = 2;
   */
  IN = 2,
}

