//*
// BeerProto
//
// Another beer format, written in protocol buffer.
//
// Copyright (c) 2020 Ross Merrigan

// @generated by protoc-gen-es v1.9.0
// @generated from file beerproto/v1/timing.proto (package beerproto.v1, syntax proto3)
/* eslint-disable */
// @ts-nocheck

import type { BinaryReadOptions, FieldList, JsonReadOptions, JsonValue, PartialMessage, PlainMessage } from "@bufbuild/protobuf";
import { Message, proto3 } from "@bufbuild/protobuf";
import type { AcidityType, GravityType, TimeType } from "./measureable_units_pb.js";

/**
 * @generated from enum beerproto.v1.UseType
 */
export declare enum UseType {
  /**
   * @generated from enum value: USE_TYPE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * add to mash
   *
   * @generated from enum value: USE_TYPE_ADD_TO_MASH = 1;
   */
  ADD_TO_MASH = 1,

  /**
   * add to boil
   *
   * @generated from enum value: USE_TYPE_ADD_TO_BOIL = 2;
   */
  ADD_TO_BOIL = 2,

  /**
   * add to fermentation
   *
   * @generated from enum value: USE_TYPE_ADD_TO_FERMENTATION = 3;
   */
  ADD_TO_FERMENTATION = 3,

  /**
   * add to package
   *
   * @generated from enum value: USE_TYPE_ADD_TO_PACKAGE = 4;
   */
  ADD_TO_PACKAGE = 4,
}

/**
 * The timing object fully describes the timing of an addition with options for basis on time, gravity, or pH at any process step
 *
 * @generated from message beerproto.v1.TimingType
 */
export declare class TimingType extends Message<TimingType> {
  /**
   * What time during a process step is added, eg a value of 2 days for a dry hop addition would be added 2 days into the fermentation step.
   *
   * @generated from field: beerproto.v1.TimeType time = 1;
   */
  time?: TimeType;

  /**
   * How long an ingredient addition remains, this was referred to as time in the BeerXML standard. E.G. A 40 minute hop boil additions means to boil for 40 minutes, and a 2 day duration for a dry hop means to remove it after 2 days.
   *
   * @generated from field: beerproto.v1.TimeType duration = 2;
   */
  duration?: TimeType;

  /**
   * A continuous addition is spread out evenly and added during the entire process step, eg 60 minute IPA by dogfish head takes all ofthe hop additions and adds them throughout the entire boil.
   *
   * @generated from field: bool continuous = 3;
   */
  continuous: boolean;

  /**
   * Used to indicate when an addition is added based on a desired specific gravity. E.G. Add dry hop at when SG is 1.018.
   *
   * @generated from field: beerproto.v1.GravityType specific_gravity = 4;
   */
  specificGravity?: GravityType;

  /**
   * Used to indicate when an addition is added based on a desired specific pH. eg Add brett when pH is 3.4.
   *
   * @generated from field: beerproto.v1.AcidityType ph = 5;
   */
  ph?: AcidityType;

  /**
   * Used to indicate what step this ingredient timing addition is referencing. EG A value of 2 for add_to_fermentation would mean to add during the second fermentation step.
   *
   * @generated from field: int32 step = 6;
   */
  step: number;

  /**
   * @generated from field: beerproto.v1.UseType use = 7;
   */
  use: UseType;

  constructor(data?: PartialMessage<TimingType>);

  static readonly runtime: typeof proto3;
  static readonly typeName = "beerproto.v1.TimingType";
  static readonly fields: FieldList;

  static fromBinary(bytes: Uint8Array, options?: Partial<BinaryReadOptions>): TimingType;

  static fromJson(jsonValue: JsonValue, options?: Partial<JsonReadOptions>): TimingType;

  static fromJsonString(jsonString: string, options?: Partial<JsonReadOptions>): TimingType;

  static equals(a: TimingType | PlainMessage<TimingType> | undefined, b: TimingType | PlainMessage<TimingType> | undefined): boolean;
}

