name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]
  workflow_dispatch:

jobs:
  Proto:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Checkout beerproto
        uses: actions/checkout@v2
        with:
          repository: beerproto/beerproto
          path: proto
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - run: npm install -g @bufbuild/protoc-gen-es
      - run: npm install
      - uses: bufbuild/buf-setup-action@v1
      - name: Buf generate
        run: buf generate beerprotoapis --template=buf.gen.es.yaml
        working-directory: ./proto
      - name: Move beer file
        run: mv ./proto/gen/proto/es/beerproto/v1/* ./src/
      - run: rm -R ./proto
      - name: Push
        uses: actions-x/commit@v6
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          branch: "master"
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: v1.${{ github.run_number }}.0
          body: CI Release ${{ github.ref }}
          draft: false
          prerelease: false
